# fly.toml app configuration file generated for hanna-blog on 2023-05-07T01:24:18-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "hanna-blog"
primary_region = "atl"

[env]
  PORT = "8080"

[http_service]
  internal_port = 1338
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
